# Generated by Django 5.2.8 on 2025-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('response', models.TextField(blank=True, verbose_name='پاسخ مدیر')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ\u200cگویی')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'دیده شده'), ('answered', 'پاسخ داده شده'), ('archived', 'آرشیوشده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت پیام')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=1000, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='contact_con_email_14aff9_idx'), models.Index(fields=['created_at'], name='contact_con_created_fddb83_idx')],
            },
        ),
    ]
