# Generated by Django 5.2.8 on 2025-12-02 02:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'نام باید حداقل ۳ کاراکتر باشد.'), django.core.validators.RegexValidator('^[a-zA-Zآ-ی\\s]+$', 'نام فقط باید شامل حروف باشد.')], verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='ایمیل وارد شده معتبر نیست.')], verbose_name='ایمیل')),
                ('sender_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP ارسال\u200cکننده')),
                ('subject', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'عنوان باید حداقل ۳ کاراکتر باشد.')], verbose_name='عنوان پیام')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'متن پیام باید حداقل ۱۰ کاراکتر باشد.')], verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('archived', 'آرشیو شده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت پیام')),
                ('reply_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال پاسخ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_con_status_402fcf_idx')],
            },
        ),
    ]
