# Generated by Django 5.2.8 on 2025-11-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_fileupload_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ URL')),
                ('content', models.TextField(blank=True, verbose_name='محتوای صفحه')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='کلمات کلیدی متا')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='نمایش در منو')),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='ریدایرکت به URL')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fileupload', verbose_name='تصویر شاخص')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['-created_at'],
            },
        ),
    ]
